import { readFile } from "node:fs/promises";
import { describe, expect, it } from "vitest";
import { compileText } from "../src/compiler.js";
import { generateAll } from "../src/build.js";

async function procurement() {
  const source = await readFile("examples/procurement.model", "utf8");
  return compileText(source, "examples/procurement.model");
}

async function reservations() {
  const source = await readFile("examples/reservations.model", "utf8");
  return compileText(source, "examples/reservations.model");
}

describe("backends", () => {
  it("generates deterministic output from IR only", async () => {
    const ir = await procurement();
    expect(generateAll(ir)).toEqual(generateAll(ir));
  });

  it("matches every committed golden artifact byte-for-byte", async () => {
    const output = generateAll(await procurement());
    for (const [path, expected] of Object.entries(output)) {
      expect(await readFile(`generated/procurement/${path}`, "utf8"), path).toBe(expected);
    }
    const reservationOutput = generateAll(await reservations());
    for (const [path, expected] of Object.entries(reservationOutput)) {
      expect(await readFile(`generated/reservations/${path}`, "utf8"), `reservations/${path}`).toBe(expected);
    }
  });

  it("emits atomic half-open temporal exclusion enforcement", async () => {
    const output = generateAll(await reservations());
    const schema = output["postgres/002_schema.sql"];
    expect(schema).toContain("CREATE EXTENSION IF NOT EXISTS btree_gist");
    expect(schema).toContain('CHECK (("starts_at" < "ends_at") IS TRUE)');
    expect(schema).toContain("EXCLUDE USING gist");
    expect(schema).toContain("tstzrange(\"starts_at\", \"ends_at\", '[)')");
    expect(output["typescript/errors.ts"]).toContain('value?.code === "23P01"');
    expect(output["typescript/errors.ts"]).toContain("class ConflictError");
    expect(output["enforcement.md"]).toContain("exclusion:exc_d55bab6e14884cd5a7d2bacfc30458ba");
    expect(output["model.mmd"]).toContain("Temporal exclusion: no_overlapping_reservations");
  });

  it("uses database-owned defaults for generated values and returns them to typed clients", async () => {
    const output = generateAll(await procurement());
    const schema = output["postgres/002_schema.sql"];
    const actions = output["postgres/003_actions.sql"];
    const types = output["typescript/types.ts"];
    expect(schema).toContain('"id" uuid NOT NULL DEFAULT pg_catalog.gen_random_uuid() PRIMARY KEY');
    expect(schema).toContain('"created_at" timestamptz NOT NULL DEFAULT pg_catalog.transaction_timestamp()');
    expect(actions).toContain('CREATE OR REPLACE FUNCTION "model_procurement"."open_request"("p_amount" numeric)');
    expect(actions).not.toContain('"p_id"');
    expect(actions).toContain("RETURNING * INTO v_result");
    expect(types).toContain('export interface OpenRequestInput {\n  amount: Money<"USD">;\n}');
    expect(types).toContain("Generated by the database using uuid; immutable after creation.");
    expect(types).toContain("Generated by the database using now; immutable after creation.");
    expect(output["enforcement.md"]).toContain("generated:field:fld_af918d24406040619a77b244a81ca5d3");
  });

  it("enforces exact currency-typed money across PostgreSQL and TypeScript", async () => {
    const output = generateAll(await procurement());
    const schema = output["postgres/002_schema.sql"];
    const actions = output["postgres/003_actions.sql"];
    const types = output["typescript/types.ts"];
    const client = output["typescript/client.ts"];
    expect(schema).toContain('"amount" numeric NOT NULL');
    expect(schema).toContain('CONSTRAINT "ck_purchase_request_amount_money"');
    expect(schema).toContain('pg_catalog.scale("amount") <= 2');
    expect(schema).toContain('pg_catalog.abs("amount") < 1000000000000000000');
    expect(actions).toContain('ML_VALIDATION:money-parameter:parameter:action:act_1e35db0451b1461e941af6283d86dca2.amount');
    expect(actions).toContain('v_request."amount" <= 10000');
    expect(actions).toContain("jsonb_build_object('currency', 'USD', 'amount'");
    expect(types).toContain("export interface Money<C extends string>");
    expect(types).toContain('amount: Money<"USD">;');
    expect(client).toContain('moneyAmount(input.amount, "USD", 20, 2');
    expect(output["typescript/errors.ts"]).toContain("class ValidationError");
    expect(output["enforcement.md"]).toContain("money:field:fld_9810e7598584487ea4a883e3c1c3f8d1");
    expect(output["enforcement.md"]).toContain("money-parameter:parameter:action:act_1e35db0451b1461e941af6283d86dca2.amount");
  });

  it("validates money parameters on generated query boundaries", () => {
    const source = `model MoneyQueries version "0.8.0";
      entity User { id: UUID @id; }
      entity Invoice { id: UUID @id; amount: Money<USD>; }
      query under(caller actor: User, ceiling: Money<USD>) from Invoice as invoice {
        authorize true;
        where invoice.amount <= ceiling;
        orderBy invoice.id asc;
        limit 10;
      }`;
    const output = generateAll(compileText(source, "money-query.model"));
    expect(output["postgres/003_queries.sql"]).toContain('CREATE OR REPLACE FUNCTION "model_money_queries"."under"("p_ceiling" numeric)');
    expect(output["postgres/003_queries.sql"]).toContain("ML_VALIDATION:money-parameter:parameter:query:under.ceiling");
    expect(output["typescript/types.ts"]).toContain('ceiling: Money<"USD">;');
    expect(output["typescript/client.ts"]).toContain('moneyAmount(input.ceiling, "USD", 20, 2');
    expect(output["enforcement.md"]).toContain("money-parameter:parameter:query:under.ceiling");
  });

  it("uses DEFAULT VALUES when a create effect assigns no fields", () => {
    const source = `model Tokens version "0.7.0";
      entity User { id: UUID @id; }
      entity Token {
        id: UUID @id @generated(uuid);
        createdAt: DateTime @generated(now);
      }
      action issue(caller actor: User) -> Token {
        authorize true;
        create Token { }
      }`;
    const sql = generateAll(compileText(source, "tokens.model"))["postgres/003_actions.sql"];
    expect(sql).toContain('INSERT INTO "model_tokens"."token" DEFAULT VALUES');
    expect(sql).toContain("RETURNING * INTO v_result");
  });

  it("lowers null checks as IS NULL and never = NULL", () => {
    const source = `model M version "1";
      entity User { id: UUID @id; }
      entity Item { id: UUID @id; owner: User?; invariant owner_optional: owner == null or owner != null; }
      action make(caller actor: User, id: UUID) -> Item {
        authorize true;
        create Item { id = id; owner = null; }
      }`;
    const sql = generateAll(compileText(source, "null.model"))["postgres/002_schema.sql"];
    expect(sql).toContain("IS NULL");
    expect(sql).toContain("IS NOT NULL");
    expect(sql).not.toMatch(/(?:=|<>) NULL/);
  });

  it("enforces exclusive lower bounds and only writes snapshots when an action assigns them", () => {
    const source = `model M version "1";
      enum Role { EMPLOYEE }
      entity User { id: UUID @id; role: Role; }
      entity Record { id: UUID @id; amount: Decimal @minExclusive(0); roleAtWrite: Role? @snapshot; }
      action make(caller actor: User, id: UUID, amount: Decimal) -> Record {
        authorize true;
        create Record { id = id; amount = amount; }
      }`;
    const output = generateAll(compileText(source, "exclusive.model"));
    expect(output["postgres/002_schema.sql"]).toContain('"amount" > 0');
    expect(output["postgres/002_schema.sql"]).toContain("ck_record_amount_min_exclusive");
    expect(output["postgres/003_actions.sql"]).not.toMatch(/INSERT INTO[\s\S]*?"role_at_write"[\s\S]*?VALUES/);
    expect(output["typescript/types.ts"]).toContain("Stored point-in-time snapshot");
  });

  it("never exposes an actor argument in SQL or TypeScript callable APIs", async () => {
    const output = generateAll(await procurement());
    const actions = output["postgres/003_actions.sql"];
    const queries = output["postgres/003_queries.sql"];
    const client = output["typescript/client.ts"];
    const types = output["typescript/types.ts"];
    expect(actions).not.toMatch(/"p_actor"/);
    expect(queries).not.toMatch(/"p_actor"/);
    expect(client).not.toMatch(/input\.actor|actor:/);
    expect(types).not.toMatch(/\n  actor:/);
    expect(actions).toContain("session_user");
    expect(queries).toContain("session_user");
    expect(actions).toContain('v_actor."id" = v_request."requester_id"');
  });

  it("emits safe privileged functions and an execute-only application boundary", async () => {
    const output = generateAll(await procurement());
    expect(output["postgres/003_actions.sql"]).toContain("SECURITY DEFINER");
    expect(output["postgres/003_actions.sql"]).toContain("SET search_path = pg_catalog, pg_temp");
    expect(output["postgres/003_actions.sql"]).not.toContain("EXECUTE ");
    expect(output["postgres/003_queries.sql"]).toContain("SECURITY DEFINER");
    expect(output["postgres/003_queries.sql"]).toContain("SET search_path = pg_catalog, pg_temp");
    expect(output["postgres/004_grants.sql"]).toContain('REVOKE ALL ON TABLE "model_procurement"."purchase_request"');
    expect(output["postgres/004_grants.sql"]).not.toContain("GRANT SELECT");
    expect(output["postgres/004_grants.sql"]).toContain('GRANT EXECUTE ON FUNCTION "model_procurement"."my_requests"()');
  });

  it("generates fail-closed, deterministic, bounded query SQL and typed clients", async () => {
    const output = generateAll(await procurement());
    const sql = output["postgres/003_queries.sql"];
    expect(sql).toContain('CREATE OR REPLACE FUNCTION "model_procurement"."my_requests"()');
    expect(sql).toContain('WHERE (((v_row."requester_id" = v_actor."id")) IS TRUE)');
    expect(sql).toContain('ORDER BY v_row."id" ASC, v_row."id" ASC');
    expect(sql).toContain("LIMIT 100");
    expect(sql).not.toMatch(/FOR (?:UPDATE|NO KEY UPDATE)/);
    expect(output["typescript/types.ts"]).toContain("export interface MyRequestsInput");
    expect(output["typescript/types.ts"]).not.toMatch(/interface MyRequestsInput \{\n  actor:/);
    expect(output["typescript/client.ts"]).toContain("async myRequests(input: MyRequestsInput): Promise<PurchaseRequest[]>");
  });

  it("enforces enum sets and lowers membership and snapshot copies", async () => {
    const output = generateAll(await procurement());
    const schema = output["postgres/002_schema.sql"];
    const actions = output["postgres/003_actions.sql"];
    expect(schema).toContain('"roles" text[] NOT NULL');
    expect(schema).toContain('CONSTRAINT "ck_user_roles_enum_set"');
    expect(schema).toContain('"roles" <@ ARRAY[\'EMPLOYEE\', \'MANAGER\', \'FINANCE\']::text[]');
    expect(schema).toContain('array_position("roles", NULL::text) IS NULL');
    expect(schema).toContain("array_positions(\"roles\", 'MANAGER')");
    expect(schema).toContain('CONSTRAINT "ck_purchase_request_approval_authority_matches_amount"');
    expect(schema).toContain("'MANAGER' = ANY(\"approved_by_roles\")");
    expect(schema).toContain('CONSTRAINT "ck_purchase_request_approver_differs_from_requester"');
    expect(actions).toContain("'EMPLOYEE' = ANY(v_actor.\"roles\")");
    expect(actions).toContain("'MANAGER' = ANY(v_actor.\"roles\")");
    expect(actions).toContain("'FINANCE' = ANY(v_actor.\"roles\")");
    expect(actions).toContain('v_actor."id" <> v_request."requester_id"');
    expect(actions).toContain('"approved_by_roles" = v_actor."roles"');
    expect(actions).toContain("'action:act_1e35db0451b1461e941af6283d86dca2'");
    expect(output["typescript/types.ts"]).toContain("roles: Role[];");
    expect(output["typescript/types.ts"]).toContain("approvedByRoles: Role[] | null;");
    expect(output["enforcement.md"]).toContain("enum-set:field:fld_b4b29a4d0d914ec0913e578da89e5dcb");
  });

  it("explains identity, locks, invariants, guards, effects, and privilege boundaries", async () => {
    const markdown = generateAll(await procurement())["enforcement.md"];
    for (const expected of [
      "boundary:principal_binding",
      "invariant:inv_b70e8aa03e6d498f8b0bccf413636b19",
      "invariant:inv_91184dc547c24978a48362a679eeb836",
      "invariant:inv_f8c6cf86f9d64874ac4159766e522cb8",
      "snapshot:field:fld_577b4c94c9cd4b469aded37614712fba",
      "authorize:action:act_d39dbb883b5f4019b9027b85add3de47",
      "require:action:act_d39dbb883b5f4019b9027b85add3de47.is_submitted",
      "lock:action:act_d39dbb883b5f4019b9027b85add3de47.request",
      "boundary:entity:ent_9bc680209327484c8e98f5f740bcc702.direct_write",
      "boundary:entity:ent_9bc680209327484c8e98f5f740bcc702.direct_read",
      "where:query:qry_4406b045404a48449282db804f6167a8",
      "order:query:qry_4406b045404a48449282db804f6167a8",
      "limit:query:qry_4406b045404a48449282db804f6167a8",
      "read:query:qry_4406b045404a48449282db804f6167a8",
      "boundary:audit",
    ]) expect(markdown).toContain(expected);
  });
});
