import type { IRAction, IREntity, IRExpression, IRField, IRParameter, ModelIR } from "../ir.js";
import { quoteIdent, snakeCase } from "../naming.js";

export interface PostgresOutput {
  "001_roles.sql": string;
  "002_schema.sql": string;
  "003_actions.sql": string;
  "004_grants.sql": string;
  "005_seed.sql": string;
}

function qname(schema: string, name: string): string {
  return `${quoteIdent(schema)}.${quoteIdent(name)}`;
}

function entityById(ir: ModelIR, id: string): IREntity {
  const value = ir.entities.find((entity) => entity.id === id);
  if (!value) throw new Error(`E4001 Unknown entity ${id}`);
  return value;
}

function fieldById(ir: ModelIR, id: string): { entity: IREntity; field: IRField } {
  for (const entity of ir.entities) {
    const field = entity.fields.find((candidate) => candidate.id === id);
    if (field) return { entity, field };
  }
  throw new Error(`E4002 Unknown field ${id}`);
}

function sqlType(type: string): string {
  if (type.startsWith("entity:")) return "uuid";
  if (type.startsWith("enum:")) return "text";
  const types: Record<string, string> = {
    String: "text", Int: "bigint", Decimal: "numeric", Boolean: "boolean", UUID: "uuid", DateTime: "timestamptz",
  };
  const result = types[type];
  if (!result) throw new Error(`E4003 Unsupported SQL type ${type}`);
  return result;
}

function sqlLiteral(expression: IRExpression): string {
  if (expression.kind === "nullLiteral") return "NULL";
  if (expression.kind === "enumLiteral") return `'${expression.member.replaceAll("'", "''")}'`;
  if (expression.kind !== "literal") throw new Error("E4004 Default is not a literal.");
  if (typeof expression.value === "string") return `'${expression.value.replaceAll("'", "''")}'`;
  if (typeof expression.value === "boolean") return expression.value ? "TRUE" : "FALSE";
  return String(expression.value);
}

interface ExpressionContext {
  ir: ModelIR;
  action?: IRAction;
  selfEntity?: IREntity;
  recordNames?: Map<string, string>;
}

function lowerExpression(expression: IRExpression, context: ExpressionContext): string {
  switch (expression.kind) {
    case "literal": return sqlLiteral(expression);
    case "nullLiteral": return "NULL";
    case "enumLiteral": return `'${expression.member.replaceAll("'", "''")}'`;
    case "parameter": {
      const parameter = context.action?.parameters.find((candidate) => candidate.id === expression.parameterId);
      if (!parameter) throw new Error(`E4005 Missing parameter ${expression.parameterId}`);
      return quoteIdent(parameter.naming.sqlParameter);
    }
    case "entityValue": {
      const record = context.recordNames?.get(expression.parameterId);
      if (!record) throw new Error(`E4006 Missing entity record ${expression.parameterId}`);
      return `${record}.${quoteIdent("id")}`;
    }
    case "fieldAccess": {
      const { field } = fieldById(context.ir, expression.fieldId);
      if (expression.source === "self") return quoteIdent(field.naming.sqlColumn);
      const record = context.recordNames?.get(expression.source);
      if (!record) throw new Error(`E4007 Missing field record ${expression.source}`);
      return `${record}.${quoteIdent(field.naming.sqlColumn)}`;
    }
    case "unary": return `(NOT ${lowerExpression(expression.operand, context)})`;
    case "binary":
      return `(${lowerExpression(expression.left, context)} ${sqlOperator(expression.operator)} ${lowerExpression(expression.right, context)})`;
    case "nullComparison":
      return `(${lowerExpression(expression.operand, context)} ${expression.operator === "isNull" ? "IS NULL" : "IS NOT NULL"})`;
  }
}

function sqlOperator(operator: Extract<IRExpression, { kind: "binary" }>["operator"]): string {
  return ({ and: "AND", or: "OR", "==": "=", "!=": "<>", "<": "<", "<=": "<=", ">": ">", ">=": ">=" } as const)[operator];
}

function generateRoles(): string {
  return `-- Generated by ModelLang. Administrative bootstrap; run as a role with CREATEROLE.
DO $modellang$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_catalog.pg_roles WHERE rolname = 'modellang_owner') THEN
    CREATE ROLE modellang_owner NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_catalog.pg_roles WHERE rolname = 'modellang_app') THEN
    CREATE ROLE modellang_app NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT;
  END IF;
END
$modellang$;

ALTER ROLE modellang_owner NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;
ALTER ROLE modellang_app NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT;
REVOKE modellang_owner FROM modellang_app;
`;
}

function generateSchema(ir: ModelIR): string {
  const schema = ir.model.naming.sqlSchema;
  const internal = ir.model.naming.internalSchema;
  const lines = [
    `-- source ${ir.model.sourceHash}`,
    ...(ir.entities.some((entity) => entity.temporalExclusions.length > 0)
      ? ["CREATE EXTENSION IF NOT EXISTS btree_gist;", ""]
      : []),
    `CREATE SCHEMA ${quoteIdent(schema)} AUTHORIZATION modellang_owner;`,
    `CREATE SCHEMA ${quoteIdent(internal)} AUTHORIZATION modellang_owner;`,
    "SET ROLE modellang_owner;",
    `REVOKE ALL ON SCHEMA ${quoteIdent(schema)} FROM PUBLIC;`,
    `REVOKE ALL ON SCHEMA ${quoteIdent(internal)} FROM PUBLIC;`,
    "",
  ];
  for (const entity of ir.entities) {
    const columns = entity.fields.map((field) => {
      const pieces = [quoteIdent(field.naming.sqlColumn), sqlType(field.type)];
      if (!field.optional) pieces.push("NOT NULL");
      if (field.default) pieces.push(`DEFAULT ${sqlLiteral(field.default)}`);
      if (field.annotations.some((annotation) => annotation.name === "id")) pieces.push("PRIMARY KEY");
      return `  ${pieces.join(" ")}`;
    });
    const constraints: string[] = [];
    for (const field of entity.fields) {
      if (field.type.startsWith("enum:")) {
        const enumeration = ir.enums.find((candidate) => candidate.id === field.type)!;
        const members = enumeration.members.map((member) => `'${member.replaceAll("'", "''")}'`).join(", ");
        const test = `${quoteIdent(field.naming.sqlColumn)} IN (${members})`;
        const optionalTest = field.optional ? `(${quoteIdent(field.naming.sqlColumn)} IS NULL OR ${test})` : test;
        constraints.push(`  CONSTRAINT ${quoteIdent(`ck_${entity.naming.sqlTable}_${field.naming.sqlColumn}_enum`)} CHECK ((${optionalTest}) IS TRUE)`);
      }
      for (const annotation of field.annotations) {
        if (annotation.name === "unique") constraints.push(`  CONSTRAINT ${quoteIdent(`uq_${entity.naming.sqlTable}_${field.naming.sqlColumn}_unique`)} UNIQUE (${quoteIdent(field.naming.sqlColumn)})`);
        if (annotation.name === "min" || annotation.name === "minExclusive") {
          const operator = annotation.name === "minExclusive" ? ">" : ">=";
          const test = `${quoteIdent(field.naming.sqlColumn)} ${operator} ${annotation.value}`;
          constraints.push(`  CONSTRAINT ${quoteIdent(`ck_${entity.naming.sqlTable}_${field.naming.sqlColumn}_${snakeCase(annotation.name)}`)} CHECK ((${field.optional ? `${quoteIdent(field.naming.sqlColumn)} IS NULL OR ${test}` : test}) IS TRUE)`);
        }
        if (annotation.name === "max") {
          const test = `${quoteIdent(field.naming.sqlColumn)} <= ${annotation.value}`;
          constraints.push(`  CONSTRAINT ${quoteIdent(`ck_${entity.naming.sqlTable}_${field.naming.sqlColumn}_max`)} CHECK ((${field.optional ? `${quoteIdent(field.naming.sqlColumn)} IS NULL OR ${test}` : test}) IS TRUE)`);
        }
      }
    }
    for (const invariant of entity.invariants) {
      constraints.push(`  CONSTRAINT ${quoteIdent(invariant.naming.sqlConstraint)} CHECK ((${lowerExpression(invariant.expression, { ir, selfEntity: entity })}) IS TRUE)`);
    }
    for (const exclusion of entity.temporalExclusions) {
      const key = fieldById(ir, exclusion.keyFieldId).field;
      const start = fieldById(ir, exclusion.startFieldId).field;
      const end = fieldById(ir, exclusion.endFieldId).field;
      constraints.push(
        `  CONSTRAINT ${quoteIdent(exclusion.naming.sqlValidIntervalConstraint)} CHECK ((${quoteIdent(start.naming.sqlColumn)} < ${quoteIdent(end.naming.sqlColumn)}) IS TRUE)`,
        `  CONSTRAINT ${quoteIdent(exclusion.naming.sqlExclusionConstraint)} EXCLUDE USING gist (${quoteIdent(key.naming.sqlColumn)} WITH =, pg_catalog.tstzrange(${quoteIdent(start.naming.sqlColumn)}, ${quoteIdent(end.naming.sqlColumn)}, '${exclusion.intervalBounds}') WITH &&)`,
      );
    }
    lines.push(`CREATE TABLE ${qname(schema, entity.naming.sqlTable)} (\n${[...columns, ...constraints].join(",\n")}\n);`, "");
  }
  for (const entity of ir.entities) {
    for (const field of entity.fields.filter((candidate) => candidate.type.startsWith("entity:"))) {
      const target = entityById(ir, field.type);
      lines.push(
        `ALTER TABLE ${qname(schema, entity.naming.sqlTable)}`,
        `  ADD CONSTRAINT ${quoteIdent(`fk_${entity.naming.sqlTable}_${field.naming.sqlColumn}`)}`,
        `  FOREIGN KEY (${quoteIdent(field.naming.sqlColumn)}) REFERENCES ${qname(schema, target.naming.sqlTable)} (${quoteIdent("id")});`,
        "",
      );
    }
  }
  const principal = entityById(ir, ir.principal.entityId);
  lines.push(
    `CREATE TABLE ${qname(internal, "principal_binding")} (`,
    `  ${quoteIdent("database_principal")} name PRIMARY KEY,`,
    `  ${quoteIdent("principal_id")} uuid NOT NULL UNIQUE REFERENCES ${qname(schema, principal.naming.sqlTable)} (${quoteIdent("id")})`,
    ");",
    "",
    `CREATE TABLE ${qname(internal, "action_audit")} (`,
    `  ${quoteIdent("id")} bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,`,
    `  ${quoteIdent("action_id")} text NOT NULL,`,
    `  ${quoteIdent("database_principal")} name NOT NULL,`,
    `  ${quoteIdent("principal_id")} uuid NOT NULL,`,
    `  ${quoteIdent("target_id")} uuid,`,
    `  ${quoteIdent("occurred_at")} timestamptz NOT NULL DEFAULT transaction_timestamp()`,
    ");",
    "RESET ROLE;",
    "",
  );
  return `${lines.join("\n")}\n`;
}

function parameterSql(parameter: IRParameter): string {
  return `${quoteIdent(parameter.naming.sqlParameter)} ${sqlType(parameter.type)}`;
}

function functionSignature(ir: ModelIR, action: IRAction): string {
  const callable = action.parameters.filter((parameter) => action.callableParameters.includes(parameter.id));
  return `${qname(ir.model.naming.sqlSchema, action.naming.sqlFunction)}(${callable.map((parameter) => sqlType(parameter.type)).join(", ")})`;
}

function rowJson(entity: IREntity, record: string): string {
  const values = entity.fields.flatMap((field) => {
    const value = `${record}.${quoteIdent(field.naming.sqlColumn)}${field.type === "Decimal" ? "::text" : ""}`;
    return [`'${field.name.replaceAll("'", "''")}'`, value];
  });
  return `jsonb_build_object(${values.join(", ")})`;
}

function generateAction(ir: ModelIR, action: IRAction): string {
  const schema = ir.model.naming.sqlSchema;
  const internal = ir.model.naming.internalSchema;
  const callable = action.parameters.filter((parameter) => action.callableParameters.includes(parameter.id));
  const recordNames = new Map<string, string>();
  for (const parameter of action.parameters.filter((candidate) => candidate.type.startsWith("entity:"))) {
    recordNames.set(parameter.id, `v_${snakeCase(parameter.name)}`);
  }
  const returnEntity = entityById(ir, action.returnEntityId);
  const declarations = [
    "  v_principal_id uuid;",
    `  v_result ${qname(schema, returnEntity.naming.sqlTable)}%ROWTYPE;`,
  ];
  for (const parameter of action.parameters.filter((candidate) => candidate.type.startsWith("entity:"))) {
    const entity = entityById(ir, parameter.type);
    declarations.push(`  ${recordNames.get(parameter.id)} ${qname(schema, entity.naming.sqlTable)}%ROWTYPE;`);
  }
  const body: string[] = [
    `  SELECT ${quoteIdent("principal_id")} INTO v_principal_id`,
    `  FROM ${qname(internal, "principal_binding")}`,
    `  WHERE ${quoteIdent("database_principal")} = session_user`,
    "  FOR SHARE;",
    "",
    "  IF NOT FOUND THEN",
    "    RAISE EXCEPTION USING ERRCODE = '42501', MESSAGE = 'ML_IDENTITY_UNBOUND';",
    "  END IF;",
    "",
  ];
  const lockGroups = new Map<string, typeof action.lockPlan>();
  for (const lock of action.lockPlan) {
    const group = lockGroups.get(lock.entityId) ?? [];
    group.push(lock);
    lockGroups.set(lock.entityId, group);
  }
  for (const [entityId, locks] of lockGroups) {
    const entity = entityById(ir, entityId);
    const mode = locks.some((lock) => lock.mode === "update") ? "UPDATE" : "SHARE";
    const ids = locks.map((lock) => {
      const parameter = action.parameters.find((candidate) => candidate.id === lock.parameterId)!;
      return parameter.caller ? "v_principal_id" : quoteIdent(parameter.naming.sqlParameter);
    });
    body.push(
      `  PERFORM ${quoteIdent("id")} FROM ${qname(schema, entity.naming.sqlTable)}`,
      `  WHERE ${quoteIdent("id")} = ANY (ARRAY[${ids.join(", ")}]::uuid[])`,
      `  ORDER BY ${quoteIdent("id")} FOR ${mode};`,
      "",
    );
  }
  for (const lock of action.lockPlan) {
    const parameter = action.parameters.find((candidate) => candidate.id === lock.parameterId)!;
    const entity = entityById(ir, parameter.type);
    const idValue = parameter.caller ? "v_principal_id" : quoteIdent(parameter.naming.sqlParameter);
    body.push(
      `  SELECT * INTO ${recordNames.get(parameter.id)}`,
      `  FROM ${qname(schema, entity.naming.sqlTable)}`,
      `  WHERE ${quoteIdent("id")} = ${idValue}`,
      ";",
      "",
      "  IF NOT FOUND THEN",
      `    RAISE EXCEPTION USING ERRCODE = 'P0002', MESSAGE = 'ML_NOT_FOUND:${parameter.name}';`,
      "  END IF;",
      "",
    );
  }
  const context = { ir, action, recordNames };
  body.push(
    `  IF NOT ((${lowerExpression(action.authorization.expression, context)}) IS TRUE) THEN`,
    `    RAISE EXCEPTION USING ERRCODE = '42501', MESSAGE = 'ML_AUTHORIZATION:${action.authorization.id}';`,
    "  END IF;",
    "",
  );
  for (const precondition of action.preconditions) {
    body.push(
      `  IF NOT ((${lowerExpression(precondition.expression, context)}) IS TRUE) THEN`,
      `    RAISE EXCEPTION USING ERRCODE = 'P0001', MESSAGE = 'ML_PRECONDITION:${precondition.id}';`,
      "  END IF;",
      "",
    );
  }
  const effectEntity = entityById(ir, action.effect.entityId);
  if (action.effect.kind === "create") {
    const fields = action.effect.assignments.map((assignment) => fieldById(ir, assignment.fieldId).field);
    body.push(
      `  INSERT INTO ${qname(schema, effectEntity.naming.sqlTable)} (${fields.map((field) => quoteIdent(field.naming.sqlColumn)).join(", ")})`,
      `  VALUES (${action.effect.assignments.map((assignment) => lowerExpression(assignment.expression, context)).join(", ")})`,
      "  RETURNING * INTO v_result;",
      "",
    );
  } else {
    const targetParameter = action.parameters.find((parameter) => parameter.name === action.effect.target)!;
    body.push(
      `  UPDATE ${qname(schema, effectEntity.naming.sqlTable)}`,
      `  SET ${action.effect.assignments.map((assignment) => {
        const field = fieldById(ir, assignment.fieldId).field;
        return `${quoteIdent(field.naming.sqlColumn)} = ${lowerExpression(assignment.expression, context)}`;
      }).join(",\n      ")}`,
      `  WHERE ${quoteIdent("id")} = ${recordNames.get(targetParameter.id)}.${quoteIdent("id")}`,
      "  RETURNING * INTO v_result;",
      "",
    );
  }
  body.push(
    `  INSERT INTO ${qname(internal, "action_audit")} (${quoteIdent("action_id")}, ${quoteIdent("database_principal")}, ${quoteIdent("principal_id")}, ${quoteIdent("target_id")})`,
    `  VALUES ('${action.id}', session_user, v_principal_id, v_result.${quoteIdent("id")});`,
    "",
    `  RETURN ${rowJson(returnEntity, "v_result")};`,
  );
  return `CREATE FUNCTION ${qname(schema, action.naming.sqlFunction)}(${callable.map(parameterSql).join(", ")})
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, pg_temp
AS $modellang$
DECLARE
${declarations.join("\n")}
BEGIN
${body.join("\n")}
END
$modellang$;

REVOKE ALL ON FUNCTION ${functionSignature(ir, action)} FROM PUBLIC;
`;
}

function generateActions(ir: ModelIR): string {
  return `-- Generated guarded action functions. Caller identity is always session_user.
SET ROLE modellang_owner;

${ir.actions.map((action) => generateAction(ir, action)).join("\n")}
RESET ROLE;
`;
}

function generateGrants(ir: ModelIR): string {
  const schema = ir.model.naming.sqlSchema;
  const internal = ir.model.naming.internalSchema;
  const lines = [
    "-- Generated least-privilege application boundary.",
    `REVOKE CREATE ON SCHEMA ${quoteIdent(schema)} FROM PUBLIC, modellang_app;`,
    `REVOKE ALL ON SCHEMA ${quoteIdent(internal)} FROM PUBLIC, modellang_app;`,
    `GRANT USAGE ON SCHEMA ${quoteIdent(schema)} TO modellang_app;`,
    "",
  ];
  for (const entity of ir.entities) {
    const table = qname(schema, entity.naming.sqlTable);
    lines.push(
      `GRANT SELECT ON TABLE ${table} TO modellang_app;`,
      `REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON TABLE ${table} FROM PUBLIC, modellang_app;`,
    );
  }
  lines.push("");
  for (const action of ir.actions) {
    lines.push(
      `REVOKE ALL ON FUNCTION ${functionSignature(ir, action)} FROM PUBLIC;`,
      `GRANT EXECUTE ON FUNCTION ${functionSignature(ir, action)} TO modellang_app;`,
    );
  }
  lines.push(
    "",
    "ALTER DEFAULT PRIVILEGES FOR ROLE modellang_owner REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;",
    "ALTER DEFAULT PRIVILEGES FOR ROLE modellang_owner REVOKE ALL ON TABLES FROM PUBLIC;",
    `REVOKE modellang_owner FROM modellang_app;`,
    "",
  );
  return `${lines.join("\n")}\n`;
}

function generateSeed(ir: ModelIR): string {
  if (ir.model.name === "Reservations") {
    const schema = ir.model.naming.sqlSchema;
    const internal = ir.model.naming.internalSchema;
    return `-- Example-only deterministic seed. Demo login roles must exist before applying this file.
SET ROLE modellang_owner;

INSERT INTO ${qname(schema, "user")} (${quoteIdent("id")}, ${quoteIdent("name")}) VALUES
  ('10000000-0000-4000-8000-000000000001', 'Reserver One'),
  ('10000000-0000-4000-8000-000000000002', 'Reserver Two');

INSERT INTO ${qname(schema, "resource")} (${quoteIdent("id")}, ${quoteIdent("name")}) VALUES
  ('20000000-0000-4000-8000-000000000001', 'Conference Room A');

INSERT INTO ${qname(internal, "principal_binding")} (${quoteIdent("database_principal")}, ${quoteIdent("principal_id")}) VALUES
  ('ml_reserver_one', '10000000-0000-4000-8000-000000000001'),
  ('ml_reserver_two', '10000000-0000-4000-8000-000000000002');

RESET ROLE;
`;
  }
  if (ir.model.name !== "Procurement") {
    return "-- Example seed data is defined only for the Procurement demonstration model.\n";
  }
  const schema = ir.model.naming.sqlSchema;
  const internal = ir.model.naming.internalSchema;
  return `-- Example-only deterministic seed. Demo login roles must exist before applying this file.
SET ROLE modellang_owner;

INSERT INTO ${qname(schema, "user")} (${quoteIdent("id")}, ${quoteIdent("name")}, ${quoteIdent("role")}) VALUES
  ('00000000-0000-4000-8000-000000000001', 'Employee One', 'EMPLOYEE'),
  ('00000000-0000-4000-8000-000000000002', 'Employee Two', 'EMPLOYEE'),
  ('00000000-0000-4000-8000-000000000003', 'Manager', 'MANAGER'),
  ('00000000-0000-4000-8000-000000000004', 'Finance', 'FINANCE');

INSERT INTO ${qname(internal, "principal_binding")} (${quoteIdent("database_principal")}, ${quoteIdent("principal_id")}) VALUES
  ('ml_employee_one', '00000000-0000-4000-8000-000000000001'),
  ('ml_employee_two', '00000000-0000-4000-8000-000000000002'),
  ('ml_manager', '00000000-0000-4000-8000-000000000003'),
  ('ml_finance', '00000000-0000-4000-8000-000000000004');

RESET ROLE;
`;
}

export function generatePostgres(ir: ModelIR): PostgresOutput {
  return {
    "001_roles.sql": generateRoles(),
    "002_schema.sql": generateSchema(ir),
    "003_actions.sql": generateActions(ir),
    "004_grants.sql": generateGrants(ir),
    "005_seed.sql": generateSeed(ir),
  };
}
