import type { IRAction, IREntity, IRField, ModelIR } from "../ir.js";

export interface TypeScriptOutput {
  "types.ts": string;
  "errors.ts": string;
  "client.ts": string;
  "index.ts": string;
}

function tsType(field: IRField): string {
  let type: string;
  if (field.type.startsWith("entity:")) type = "string";
  else if (field.type.startsWith("enum:")) type = field.type.slice(5);
  else type = ({ String: "string", Int: "number", Decimal: "string", Boolean: "boolean", UUID: "string", DateTime: "string" } as Record<string, string>)[field.type] ?? "never";
  return field.optional ? `${type} | null` : type;
}

function parameterType(type: string): string {
  if (type.startsWith("entity:")) return "string";
  if (type.startsWith("enum:")) return type.slice(5);
  return ({ String: "string", Int: "number", Decimal: "string", Boolean: "boolean", UUID: "string", DateTime: "string" } as Record<string, string>)[type] ?? "never";
}

function inputName(action: IRAction): string {
  return `${action.name[0]!.toUpperCase()}${action.name.slice(1)}Input`;
}

function generateTypes(ir: ModelIR): string {
  const lines = ["// Generated by ModelLang. Do not edit.", ""];
  for (const enumeration of ir.enums) {
    lines.push(`export type ${enumeration.name} = ${enumeration.members.map((member) => JSON.stringify(member)).join(" | ")};`, "");
  }
  for (const entity of ir.entities) {
    lines.push(`export interface ${entity.name} {`);
    for (const field of entity.fields) {
      if (field.storage === "snapshot") lines.push("  /** Stored point-in-time snapshot; it is not re-derived from a related entity. */");
      lines.push(`  ${field.name}: ${tsType(field)};`);
    }
    lines.push("}", "");
  }
  for (const action of ir.actions) {
    lines.push(`export interface ${inputName(action)} {`);
    for (const id of action.callableParameters) {
      const parameter = action.parameters.find((candidate) => candidate.id === id)!;
      lines.push(`  ${parameter.name}: ${parameterType(parameter.type)};`);
    }
    lines.push("}", "");
  }
  return `${lines.join("\n")}\n`;
}

const errorsSource = `// Generated by ModelLang. Do not edit.
export class ModelDatabaseError extends Error {
  constructor(message: string, readonly code?: string, readonly ruleId?: string, readonly cause?: unknown) {
    super(message);
    this.name = new.target.name;
  }
}
export class IdentityBindingError extends ModelDatabaseError {}
export class AuthorizationError extends ModelDatabaseError {}
export class PreconditionError extends ModelDatabaseError {}
export class InvariantError extends ModelDatabaseError {}
export class NotFoundError extends ModelDatabaseError {}

interface DatabaseFailure { code?: string; message?: string; constraint?: string }
export function mapDatabaseError(error: unknown): ModelDatabaseError {
  const value = error as DatabaseFailure;
  const message = value?.message ?? "Model database operation failed";
  const suffix = message.includes(":") ? message.slice(message.indexOf(":") + 1) : undefined;
  if (message.startsWith("ML_IDENTITY_UNBOUND")) return new IdentityBindingError(message, value.code, "boundary:principal_binding", error);
  if (message.startsWith("ML_AUTHORIZATION:")) return new AuthorizationError(message, value.code, suffix, error);
  if (message.startsWith("ML_PRECONDITION:")) return new PreconditionError(message, value.code, suffix, error);
  if (message.startsWith("ML_NOT_FOUND:")) return new NotFoundError(message, value.code, suffix, error);
  if (value?.code === "23514" || value?.code === "23502" || value?.code === "23503" || value?.code === "23505") {
    return new InvariantError(message, value.code, value.constraint, error);
  }
  return new ModelDatabaseError(message, value?.code, undefined, error);
}
`;

function actionMethod(ir: ModelIR, action: IRAction): string {
  const returnEntity = ir.entities.find((entity) => entity.id === action.returnEntityId)!;
  const args = action.callableParameters.map((id, index) => {
    const parameter = action.parameters.find((candidate) => candidate.id === id)!;
    return { parameter, placeholder: `$${index + 1}` };
  });
  const schema = ir.model.naming.sqlSchema.replaceAll('"', '""');
  const fn = action.naming.sqlFunction.replaceAll('"', '""');
  return `  async ${action.name}(input: ${inputName(action)}): Promise<${returnEntity.name}> {
    try {
      const result = await this.adapter.query<{ value: ${returnEntity.name} }>(
        'SELECT "${schema}"."${fn}"(${args.map((arg) => arg.placeholder).join(", ")}) AS value',
        [${args.map((arg) => `input.${arg.parameter.name}`).join(", ")}],
      );
      return result.rows[0]!.value;
    } catch (error) {
      throw mapDatabaseError(error);
    }
  }`;
}

function generateClient(ir: ModelIR): string {
  const imports = [
    ...ir.entities.map((entity) => entity.name),
    ...ir.actions.map(inputName),
  ];
  return `// Generated by ModelLang. Do not edit.
import type { ${imports.join(", ")} } from "./types.js";
import { mapDatabaseError } from "./errors.js";

export interface QueryAdapter {
  query<Row = unknown>(text: string, values?: unknown[]): Promise<{ rows: Row[] }>;
}

export class ${ir.model.name}Client {
  constructor(private readonly adapter: QueryAdapter) {}

${ir.actions.map((action) => actionMethod(ir, action)).join("\n\n")}
}
`;
}

export function generateTypeScript(ir: ModelIR): TypeScriptOutput {
  return {
    "types.ts": generateTypes(ir),
    "errors.ts": errorsSource,
    "client.ts": generateClient(ir),
    "index.ts": `export * from "./types.js";\nexport * from "./errors.js";\nexport * from "./client.js";\n`,
  };
}
