import type { IRAction, IRField, IRQuery, ModelIR } from "../ir.js";
import { stableJson } from "../ir.js";
import type { CapabilityManifest } from "../capability-manifest.js";
import { decisionAction, decisionFunctionName, type DecisionPlan } from "../decision-plan.js";
import { isMoneyType, moneyProfileFromType } from "../money.js";
import { operationInputName } from "../operation-manifest.js";

export interface TypeScriptOutput {
  "types.ts": string;
  "errors.ts": string;
  "client.ts": string;
  "gateway.ts": string;
  "capabilities.ts": string;
  "workflows.ts": string;
  "events.ts": string;
  "consumers.ts": string;
  "index.ts": string;
}

function enumName(ir: ModelIR, type: string): string {
  const enumId = type.startsWith("set:") ? type.slice("set:".length) : type;
  return ir.enums.find((enumeration) => enumeration.id === enumId)?.naming.typescriptName ?? "never";
}

function tsType(ir: ModelIR, field: IRField): string {
  let type: string;
  if (field.type.startsWith("entity:")) type = "string";
  else if (field.type.startsWith("set:enum:")) type = `${enumName(ir, field.type)}[]`;
  else if (field.type.startsWith("enum:")) type = enumName(ir, field.type);
  else if (isMoneyType(field.type)) type = `Money<${JSON.stringify(moneyProfileFromType(field.type)!.currency)}>`;
  else type = ({ String: "string", Int: "number", Decimal: "string", Boolean: "boolean", UUID: "string", DateTime: "string" } as Record<string, string>)[field.type] ?? "never";
  return field.optional ? `${type} | null` : type;
}

function parameterType(ir: ModelIR, type: string): string {
  if (type.startsWith("entity:")) return "string";
  if (type.startsWith("set:enum:")) return `${enumName(ir, type)}[]`;
  if (type.startsWith("enum:")) return enumName(ir, type);
  if (isMoneyType(type)) return `Money<${JSON.stringify(moneyProfileFromType(type)!.currency)}>`;
  return ({ String: "string", Int: "number", Decimal: "string", Boolean: "boolean", UUID: "string", DateTime: "string" } as Record<string, string>)[type] ?? "never";
}

function generateTypes(ir: ModelIR): string {
  const lines = [
    "// Generated by ModelLang. Do not edit.",
    "",
    'export type ApplicabilityStatus = "applicable" | "denied" | "notApplicable" | "stale";',
    'export type ApplicabilityExplanationKind = "authorization" | "requirement" | "revision";',
    "export interface ApplicabilityDecision {",
    "  readonly operationId: string;",
    "  readonly status: ApplicabilityStatus;",
    "  readonly applicable: boolean;",
    '  readonly authority: "none";',
    "  readonly revision?: string;",
    "  readonly explanation?: { readonly kind: ApplicabilityExplanationKind; readonly ruleId: string };",
    "}",
    "export interface ExecutionOptions {",
    "  readonly expectedRevision?: string;",
    "  readonly idempotencyKey?: string;",
    "  readonly correlationId?: string;",
    "  readonly causationId?: string;",
    "}",
    "export interface ApplicabilityOptions { readonly expectedRevision?: string; }",
    "",
  ];
  if (ir.entities.some((entity) => entity.fields.some((field) => isMoneyType(field.type)))
    || [...ir.actions, ...ir.queries].some((operation) => operation.parameters.some((parameter) => isMoneyType(parameter.type)))) {
    lines.push(
      "export interface Money<C extends string> {",
      "  readonly currency: C;",
      "  /** Exact base-10 amount; exponent notation and excess fractional digits are invalid. */",
      "  readonly amount: string;",
      "}",
      "",
    );
  }
  for (const enumeration of ir.enums) {
    lines.push(`export type ${enumeration.name} = ${enumeration.members.map((member) => JSON.stringify(member.naming.typescriptValue)).join(" | ")};`, "");
  }
  for (const entity of ir.entities) {
    lines.push(`export interface ${entity.name} {`);
    for (const field of entity.fields) {
      if (field.storage === "snapshot") lines.push("  /** Stored point-in-time snapshot; it is not re-derived from a related entity. */");
      if (field.generation) lines.push(`  /** Generated by the database using ${field.generation.strategy}; immutable after creation. */`);
      else if (field.mutability === "immutable") lines.push("  /** Immutable after creation. */");
      lines.push(`  ${field.name}: ${tsType(ir, field)};`);
    }
    lines.push("}", "");
  }
  for (const action of ir.actions) {
    lines.push(`export interface ${operationInputName(action)} {`);
    for (const id of action.callableParameters) {
      const parameter = action.parameters.find((candidate) => candidate.id === id)!;
      lines.push(`  ${parameter.name}: ${parameterType(ir, parameter.type)};`);
    }
    lines.push("}", "");
  }
  for (const query of ir.queries) {
    lines.push(`export interface ${operationInputName(query)} {`);
    for (const id of query.callableParameters) {
      const parameter = query.parameters.find((candidate) => candidate.id === id)!;
      lines.push(`  ${parameter.name}: ${parameterType(ir, parameter.type)};`);
    }
    lines.push("}", "");
  }
  return `${lines.join("\n")}\n`;
}

const errorsSource = `// Generated by ModelLang. Do not edit.
export class ModelOperationError extends Error {
  constructor(message: string, readonly code?: string, readonly ruleId?: string, readonly cause?: unknown) {
    super(message);
    this.name = new.target.name;
  }
}
/** @deprecated Use ModelOperationError for transport-neutral code. */
export class ModelDatabaseError extends ModelOperationError {}
export class AuthenticationError extends ModelOperationError {}
export class IdentityBindingError extends ModelDatabaseError {}
export class AuthorizationError extends ModelDatabaseError {}
export class PreconditionError extends ModelDatabaseError {}
export class TransitionError extends ModelDatabaseError {}
export class InvariantError extends ModelDatabaseError {}
export class ConflictError extends ModelDatabaseError {}
export class IdempotencyConflictError extends ConflictError {}
export class StaleError extends ConflictError {}
export class NotFoundError extends ModelDatabaseError {}
export class ValidationError extends ModelDatabaseError {}

interface DatabaseFailure { code?: string; message?: string; constraint?: string }
export function mapDatabaseError(error: unknown): ModelOperationError {
  if (error instanceof ModelOperationError) return error;
  const value = error as DatabaseFailure;
  const message = value?.message ?? "Model database operation failed";
  const suffix = message.includes(":") ? message.slice(message.indexOf(":") + 1) : undefined;
  if (message.startsWith("ML_IDENTITY_UNBOUND")) return new IdentityBindingError(message, value.code, "boundary:principal_binding", error);
  if (message.startsWith("ML_AUTHORIZATION:")) return new AuthorizationError(message, value.code, suffix, error);
  if (message.startsWith("ML_PRECONDITION:")) return new PreconditionError(message, value.code, suffix, error);
  if (message.startsWith("ML_WORKFLOW:")) return new TransitionError(message, value.code, suffix, error);
  if (message.startsWith("ML_NOT_FOUND:")) return new NotFoundError(message, value.code, suffix, error);
  if (message.startsWith("ML_VALIDATION:")) return new ValidationError(message, value.code, suffix, error);
  if (message.startsWith("ML_IDEMPOTENCY_REQUIRED:") || message.startsWith("ML_IDEMPOTENCY_UNSUPPORTED:")) return new ValidationError(message, value.code, suffix, error);
  if (message.startsWith("ML_IDEMPOTENCY_CONFLICT:")) return new IdempotencyConflictError(message, value.code, suffix, error);
  if (message.startsWith("ML_STALE:")) return new StaleError(message, value.code, suffix, error);
  if (value?.code === "23P01") return new ConflictError(message, value.code, value.constraint, error);
  if (value?.code === "23514" || value?.code === "23502" || value?.code === "23503" || value?.code === "23505") {
    return new InvariantError(message, value.code, value.constraint, error);
  }
  return new ModelDatabaseError(message, value?.code, undefined, error);
}

export interface ModelProblem {
  type: string;
  title: string;
  status: number;
  detail?: string;
  code?: string;
  ruleId?: string;
}

export function mapHttpProblem(problem: unknown, httpStatus: number): ModelOperationError {
  const value = problem && typeof problem === "object" ? problem as Partial<ModelProblem> : {};
  const message = typeof value.title === "string" ? value.title : \`Model operation failed with HTTP \${httpStatus}\`;
  const code = typeof value.code === "string" ? value.code : undefined;
  const ruleId = typeof value.ruleId === "string" ? value.ruleId : undefined;
  const type = typeof value.type === "string" ? value.type : "";
  if (type.endsWith("/authentication")) return new AuthenticationError(message, code, ruleId, problem);
  if (type.endsWith("/identity-binding")) return new IdentityBindingError(message, code, ruleId, problem);
  if (type.endsWith("/authorization")) return new AuthorizationError(message, code, ruleId, problem);
  if (type.endsWith("/precondition")) return new PreconditionError(message, code, ruleId, problem);
  if (type.endsWith("/transition")) return new TransitionError(message, code, ruleId, problem);
  if (type.endsWith("/invariant")) return new InvariantError(message, code, ruleId, problem);
  if (type.endsWith("/conflict")) return new ConflictError(message, code, ruleId, problem);
  if (type.endsWith("/idempotency-conflict")) return new IdempotencyConflictError(message, code, ruleId, problem);
  if (type.endsWith("/stale")) return new StaleError(message, code, ruleId, problem);
  if (type.endsWith("/not-found")) return new NotFoundError(message, code, ruleId, problem);
  if (type.endsWith("/validation")) return new ValidationError(message, code, ruleId, problem);
  if (type.endsWith("/method-not-allowed") || type.endsWith("/request-too-large") || type.endsWith("/unsupported-media-type")) {
    return new ValidationError(message, code, ruleId, problem);
  }
  return new ModelOperationError(message, code, ruleId, problem);
}
`;

function clientParameterValue(parameter: { id: string; name: string; type: string }): string {
  if (!isMoneyType(parameter.type)) return `input.${parameter.name}`;
  const profile = moneyProfileFromType(parameter.type)!;
  return `moneyAmount(input.${parameter.name}, ${JSON.stringify(profile.currency)}, ${profile.precision}, ${profile.scale}, ${JSON.stringify(`money-parameter:${parameter.id}`)})`;
}

function actionMethod(ir: ModelIR, action: IRAction): string {
  const returnEntity = ir.entities.find((entity) => entity.id === action.returnEntityId)!;
  const args = action.callableParameters.map((id, index) => {
    const parameter = action.parameters.find((candidate) => candidate.id === id)!;
    return { parameter, placeholder: `$${index + 1}` };
  });
  const schema = ir.model.naming.sqlSchema.replaceAll('"', '""');
  const fn = action.naming.sqlFunction.replaceAll('"', '""');
  const metadataStart = args.length + 1;
  const sql = `WITH execution_context AS MATERIALIZED (SELECT `
    + `pg_catalog.set_config('modellang.expected_revision', $${metadataStart}, true), `
    + `pg_catalog.set_config('modellang.idempotency_key', $${metadataStart + 1}, true), `
    + `pg_catalog.set_config('modellang.correlation_id', $${metadataStart + 2}, true), `
    + `pg_catalog.set_config('modellang.causation_id', $${metadataStart + 3}, true)) `
    + `SELECT "${schema}"."${fn}"(${args.map((arg) => arg.placeholder).join(", ")}) AS value FROM execution_context`;
  return `  async ${action.name}(input: ${operationInputName(action)}, options: ExecutionOptions = {}): Promise<${returnEntity.name}> {
    try {
      const metadata = executionMetadata(options, ${action.idempotency ? "true" : "false"}, ${JSON.stringify(`idempotency:${action.id}`)});
      const result = await this.adapter.query<{ value: ${returnEntity.name} }>(
        ${JSON.stringify(sql)},
        [${[...args.map((arg) => clientParameterValue(arg.parameter)), 'options.expectedRevision ?? ""', "metadata.idempotencyKey", "metadata.correlationId", "metadata.causationId"].join(", ")}],
      );
      return result.rows[0]!.value;
    } catch (error) {
      throw mapDatabaseError(error);
    }
}`;
}

function applicabilityMethod(ir: ModelIR, action: IRAction, plan: DecisionPlan): string {
  const decision = decisionAction(plan, action.id);
  const args = action.callableParameters.map((id, index) => {
    const parameter = action.parameters.find((candidate) => candidate.id === id)!;
    return { parameter, placeholder: `$${index + 1}` };
  });
  const schema = ir.model.naming.sqlSchema.replaceAll('"', '""');
  const fn = decisionFunctionName(decision.operationId).replaceAll('"', '""');
  return `  async assess${action.name[0]!.toUpperCase()}${action.name.slice(1)}(input: ${operationInputName(action)}, options: ApplicabilityOptions = {}): Promise<ApplicabilityDecision> {
    try {
      const result = await this.adapter.query<{ value: ApplicabilityDecision }>(
        'SELECT "${schema}"."${fn}"(${[...args.map((arg) => arg.placeholder), `$${args.length + 1}`].join(", ")}) AS value',
        [${[...args.map((arg) => clientParameterValue(arg.parameter)), "options.expectedRevision ?? null"].join(", ")}],
      );
      return result.rows[0]!.value;
    } catch (error) {
      throw mapDatabaseError(error);
    }
  }`;
}

function queryMethod(ir: ModelIR, query: IRQuery): string {
  const sourceEntity = ir.entities.find((entity) => entity.id === query.sourceEntityId)!;
  const args = query.callableParameters.map((id, index) => {
    const parameter = query.parameters.find((candidate) => candidate.id === id)!;
    return { parameter, placeholder: `$${index + 1}` };
  });
  const schema = ir.model.naming.sqlSchema.replaceAll('"', '""');
  const fn = query.naming.sqlFunction.replaceAll('"', '""');
  return `  async ${query.name}(input: ${operationInputName(query)}): Promise<${sourceEntity.name}[]> {
    try {
      const result = await this.adapter.query<{ value: ${sourceEntity.name}[] }>(
        'SELECT "${schema}"."${fn}"(${args.map((arg) => arg.placeholder).join(", ")}) AS value',
        [${args.map((arg) => clientParameterValue(arg.parameter)).join(", ")}],
      );
      return result.rows[0]!.value;
    } catch (error) {
      throw mapDatabaseError(error);
    }
  }`;
}

function generateClient(ir: ModelIR, plan: DecisionPlan): string {
  const imports = [...new Set([
    ...ir.entities.map((entity) => entity.name),
    ...ir.actions.map(operationInputName),
    ...ir.queries.map(operationInputName),
    "ApplicabilityDecision",
    "ApplicabilityOptions",
    "ExecutionOptions",
  ])];
  const hasMoneyInputs = [...ir.actions, ...ir.queries].some((operation) =>
    operation.callableParameters.some((id) => isMoneyType(operation.parameters.find((parameter) => parameter.id === id)!.type)));
  const moneyHelper = hasMoneyInputs ? `
function moneyAmount(
  value: { currency: string; amount: string },
  expectedCurrency: string,
  precision: number,
  scale: number,
  ruleId: string,
): string {
  const match = typeof value?.amount === "string"
    ? /^-?(0|[1-9][0-9]*)(?:\\.([0-9]+))?$/.exec(value.amount)
    : null;
  const integralDigits = match ? (match[1] === "0" ? 1 : match[1]!.length) : 0;
  const fractionalDigits = match?.[2]?.length ?? 0;
  if (value?.currency !== expectedCurrency || !match
    || integralDigits > precision - scale || fractionalDigits > scale) {
    throw new ValidationError(
      \`Invalid \${expectedCurrency} money value for \${ruleId}\`,
      undefined,
      ruleId,
    );
  }
  return value.amount;
}
` : "";
  const executionHelper = `
const commandMetadataPattern = /^[A-Za-z0-9][A-Za-z0-9._:/-]{0,127}$/;
function executionMetadata(options: ExecutionOptions, required: boolean, ruleId: string): {
  idempotencyKey: string;
  correlationId: string;
  causationId: string;
} {
  const key = options.idempotencyKey ?? "";
  if (required && !key) throw new ValidationError("An idempotency key is required", "ML_IDEMPOTENCY_REQUIRED", ruleId);
  if (!required && key) throw new ValidationError("This action does not support idempotency keys", "ML_IDEMPOTENCY_UNSUPPORTED", ruleId);
  const correlation = options.correlationId ?? (required ? key : "");
  const causation = options.causationId ?? "";
  if ((key && !commandMetadataPattern.test(key))
    || (correlation && !commandMetadataPattern.test(correlation))
    || (causation && !commandMetadataPattern.test(causation))) {
    throw new ValidationError("Command metadata is invalid", "ML_VALIDATION", ruleId);
  }
  return { idempotencyKey: key, correlationId: correlation, causationId: causation };
}
`;
  return `// Generated by ModelLang. Do not edit.
import type { ${imports.join(", ")} } from "./types.js";
import { ValidationError, mapDatabaseError } from "./errors.js";

export interface QueryAdapter {
  query<Row = unknown>(text: string, values?: unknown[]): Promise<{ rows: Row[] }>;
}
${moneyHelper}
${executionHelper}

export class ${ir.model.name}Client {
  constructor(private readonly adapter: QueryAdapter) {}

${[
    ...ir.actions.map((action) => actionMethod(ir, action)),
    ...ir.actions.map((action) => applicabilityMethod(ir, action, plan)),
    ...ir.queries.map((query) => queryMethod(ir, query)),
  ].join("\n\n")}
}
`;
}

function generateGateway(ir: ModelIR): string {
  const inputImports = [...ir.actions, ...ir.queries].map(operationInputName);
  const dispatch = [
    ...ir.actions.map((operation) =>
      `        case ${JSON.stringify(operation.id)}: result = await client.${operation.name}(input as unknown as ${operationInputName(operation)}, options); break;`),
    ...ir.queries.map((operation) =>
      `        case ${JSON.stringify(operation.id)}: result = await client.${operation.name}(input as unknown as ${operationInputName(operation)}); break;`),
  ].join("\n");
  const assessDispatch = ir.actions.map((operation) =>
    `        case ${JSON.stringify(operation.id)}: result = await client.assess${operation.name[0]!.toUpperCase()}${operation.name.slice(1)}(input as unknown as ${operationInputName(operation)}, options); break;`,
  ).join("\n");
  const internal = ir.model.naming.internalSchema.replaceAll('"', '""');
  return `// Generated by ModelLang. Do not edit. Server-only PostgreSQL gateway adapter.
import type { ${[...inputImports, "ApplicabilityDecision", "ApplicabilityOptions", "ExecutionOptions"].join(", ")} } from "./types.js";
import { ${ir.model.name}Client, type QueryAdapter } from "./client.js";
import { ValidationError, mapDatabaseError } from "./errors.js";
import type { ${ir.model.name}OperationExecutor } from "./http-server.js";

export interface VerifiedGatewayIdentity {
  /** Stable issuer identifier from a successfully verified authentication token. */
  readonly issuer: string;
  /** Stable subject identifier from the same successfully verified token. */
  readonly subject: string;
}

export interface GatewayConnection extends QueryAdapter {
  release(error?: Error | boolean): void;
}

export interface GatewayPool {
  connect(): Promise<GatewayConnection>;
}

function gatewayIdentity(identity: VerifiedGatewayIdentity): VerifiedGatewayIdentity {
  if (typeof identity?.issuer !== "string" || identity.issuer.length < 1 || identity.issuer.length > 512
    || typeof identity?.subject !== "string" || identity.subject.length < 1 || identity.subject.length > 512) {
    throw new ValidationError("Verified gateway identity is invalid", "ML_VALIDATION", "boundary:gateway_identity");
  }
  return Object.freeze({ issuer: identity.issuer, subject: identity.subject });
}

export function create${ir.model.name}GatewayExecutor(
  pool: GatewayPool,
  verifiedIdentity: VerifiedGatewayIdentity,
): ${ir.model.name}OperationExecutor {
  const identity = gatewayIdentity(verifiedIdentity);
  return {
    async execute(operationId, input, options: ExecutionOptions = {}) {
      const connection = await pool.connect();
      let transactionOpen = false;
      let discardConnection = false;
      try {
        await connection.query("BEGIN");
        transactionOpen = true;
        await connection.query(
          'SELECT "${internal}"."bind_gateway_identity"($1, $2)',
          [identity.issuer, identity.subject],
        );
        const client = new ${ir.model.name}Client(connection);
        let result: unknown;
        switch (operationId) {
${dispatch}
        }
        await connection.query("COMMIT");
        transactionOpen = false;
        return result;
      } catch (error) {
        if (transactionOpen) {
          try {
            await connection.query("ROLLBACK");
          } catch {
            discardConnection = true;
          }
        } else discardConnection = true;
        throw mapDatabaseError(error);
      } finally {
        connection.release(discardConnection || undefined);
      }
    },
    async assess(operationId, input, options: ApplicabilityOptions = {}): Promise<ApplicabilityDecision> {
      const connection = await pool.connect();
      let transactionOpen = false;
      let discardConnection = false;
      try {
        await connection.query("BEGIN");
        transactionOpen = true;
        await connection.query(
          'SELECT "${internal}"."bind_gateway_identity"($1, $2)',
          [identity.issuer, identity.subject],
        );
        const client = new ${ir.model.name}Client(connection);
        let result!: ApplicabilityDecision;
        switch (operationId) {
${assessDispatch}
        }
        await connection.query("COMMIT");
        transactionOpen = false;
        return result;
      } catch (error) {
        if (transactionOpen) {
          try {
            await connection.query("ROLLBACK");
          } catch {
            discardConnection = true;
          }
        } else discardConnection = true;
        throw mapDatabaseError(error);
      } finally {
        connection.release(discardConnection || undefined);
      }
    },
  };
}
`;
}

function generateWorkflows(ir: ModelIR): string {
  const lines = ["// Generated by ModelLang. Do not edit.", ""];
  for (const workflow of ir.workflows) {
    const enumeration = ir.enums.find((candidate) => candidate.id === workflow.enumId)!;
    const memberName = (id: string) => enumeration.members.find((candidate) => candidate.id === id)!.name;
    const actionName = (id: string) => ir.actions.find((candidate) => candidate.id === id)!.name;
    lines.push(
      `export const ${workflow.naming.typescriptName} = {`,
      `  initial: ${JSON.stringify(memberName(workflow.initialMemberId))},`,
      "  transitions: [",
      ...workflow.transitions.map((transition) =>
        `    { name: ${JSON.stringify(transition.name)}, from: ${JSON.stringify(memberName(transition.fromMemberId))}, to: ${JSON.stringify(memberName(transition.toMemberId))}, action: ${JSON.stringify(actionName(transition.actionId))} },`),
      "  ],",
      "} as const;",
      "",
    );
  }
  return `${lines.join("\n").trimEnd()}\n`;
}

function generateCapabilities(capabilities: CapabilityManifest): string {
  return `// Generated by ModelLang. Do not edit. Safe public capability contract.\nexport const capabilityManifest = ${stableJson(capabilities)} as const;\n`;
}

function generateEvents(ir: ModelIR): string {
  const payloadTypes = [...new Set(ir.events.map((event) => ir.entities.find((entity) => entity.id === event.payloadEntityId)!.name))];
  const lines = [
    "// Generated by ModelLang. Do not edit.",
    ...(payloadTypes.length ? [`import type { ${payloadTypes.join(", ")} } from \"./types.js\";`, ""] : []),
    "export interface DomainEventEnvelope<EventId extends string, EventName extends string, ModelId extends string, ModelVersion extends string, SourceHash extends string, Payload> {",
    "  readonly id: string;",
    "  readonly eventId: EventId;",
    "  readonly eventName: EventName;",
    "  readonly modelId: ModelId;",
    "  readonly modelVersion: ModelVersion;",
    "  readonly sourceHash: SourceHash;",
    "  readonly actionId: string;",
    "  readonly targetId: string;",
    "  readonly payload: Payload;",
    "  readonly correlationId: string;",
    "  readonly causationId: string | null;",
    "  readonly occurredAt: string;",
    "  readonly ordinal: number;",
    "  readonly deliveryAttempt: number;",
    "}",
    "",
  ];
  const aliases = ir.events.map((event) => {
    const entity = ir.entities.find((candidate) => candidate.id === event.payloadEntityId)!;
    const alias = `${event.naming.typescriptName}Event`;
    const source = event.source.kind === "local"
      ? { modelId: ir.model.id, modelVersion: ir.model.version, sourceHash: ir.model.sourceHash }
      : event.source;
    lines.push(`export type ${alias} = DomainEventEnvelope<${JSON.stringify(event.id)}, ${JSON.stringify(event.name)}, ${JSON.stringify(source.modelId)}, ${JSON.stringify(source.modelVersion)}, ${JSON.stringify(source.sourceHash)}, ${entity.name}>;`, "");
    return alias;
  });
  lines.push(`export type ${ir.model.name}DomainEvent = ${aliases.length ? aliases.join(" | ") : "never"};`);
  return `${lines.join("\n")}\n`;
}

function generateConsumers(ir: ModelIR): string {
  const eventAliases = [...new Set(ir.consumers.map((consumer) => {
    const event = ir.events.find((candidate) => candidate.id === consumer.sourceEventId)!;
    return `${event.naming.typescriptName}Event`;
  }))];
  const resultTypes = [...new Set(ir.consumers.map((consumer) =>
    ir.entities.find((entity) => entity.id === consumer.returnEntityId)!.name))];
  const imports = [...eventAliases, ...resultTypes];
  const lines = [
    "// Generated by ModelLang. Do not edit. Server-only broker-neutral consumer adapter.",
    ...(eventAliases.length ? [`import type { ${eventAliases.join(", ")} } from \"./events.js\";`] : []),
    ...(resultTypes.length ? [`import type { ${resultTypes.join(", ")} } from \"./types.js\";`] : []),
    ...(imports.length ? [""] : []),
    "export interface ConsumerDatabaseClient {",
    "  query<Row = unknown>(text: string, values?: unknown[]): Promise<{ rows: Row[] }>;",
    "}",
    "",
    "function privateFailureCode(error: unknown): string {",
    "  const message = error instanceof Error ? error.message : String(error);",
    "  return message.match(/ML_[A-Z_]+/)?.[0] ?? \"ML_CONSUMER_HANDLER\";",
    "}",
    "",
  ];
  for (const consumer of ir.consumers) {
    const event = ir.events.find((candidate) => candidate.id === consumer.sourceEventId)!;
    const result = ir.entities.find((entity) => entity.id === consumer.returnEntityId)!;
    const functionName = `consume${consumer.name[0]!.toUpperCase()}${consumer.name.slice(1)}`;
    lines.push(
      `export async function ${functionName}(client: ConsumerDatabaseClient, event: ${event.naming.typescriptName}Event): Promise<${result.name}> {`,
      "  try {",
      `    const response = await client.query<{ result: ${result.name} }>(\"SELECT \\\"${ir.model.naming.internalSchema}\\\".\\\"${consumer.naming.sqlFunction}\\\"($1::jsonb) AS result\", [event]);`,
      "    if (response.rows.length !== 1) throw new Error(\"ML_CONSUMER_PROTOCOL\");",
      "    return response.rows[0]!.result;",
      "  } catch (error) {",
      "    try {",
      `      await client.query(\"SELECT \\\"${ir.model.naming.internalSchema}\\\".\\\"record_consumer_failure\\\"($1, $2, $3, $4)\", [${JSON.stringify(consumer.id)}, event.id, event.deliveryAttempt, privateFailureCode(error)]);`,
      "    } catch { /* Failure telemetry is private and best effort; handler failure remains authoritative. */ }",
      "    throw error;",
      "  }",
      "}",
      "",
    );
  }
  return `${lines.join("\n").trimEnd()}\n`;
}

export function generateTypeScript(ir: ModelIR, plan: DecisionPlan, capabilities: CapabilityManifest): TypeScriptOutput {
  return {
    "types.ts": generateTypes(ir),
    "errors.ts": errorsSource,
    "client.ts": generateClient(ir, plan),
    "gateway.ts": generateGateway(ir),
    "capabilities.ts": generateCapabilities(capabilities),
    "workflows.ts": generateWorkflows(ir),
    "events.ts": generateEvents(ir),
    "consumers.ts": generateConsumers(ir),
    "index.ts": `export * from "./types.js";\nexport * from "./errors.js";\nexport * from "./client.js";\nexport * from "./gateway.js";\nexport * from "./http-client.js";\nexport * from "./http-server.js";\nexport * from "./workflows.js";\nexport * from "./events.js";\nexport * from "./consumers.js";\nexport * from "./ui.js";\nexport * from "./capabilities.js";\n`,
  };
}
