import type { IRAction, IRField, IRQuery, ModelIR } from "../ir.js";
import { isMoneyType, moneyProfileFromType } from "../money.js";

export interface TypeScriptOutput {
  "types.ts": string;
  "errors.ts": string;
  "client.ts": string;
  "workflows.ts": string;
  "index.ts": string;
}

function enumName(ir: ModelIR, type: string): string {
  const enumId = type.startsWith("set:") ? type.slice("set:".length) : type;
  return ir.enums.find((enumeration) => enumeration.id === enumId)?.naming.typescriptName ?? "never";
}

function tsType(ir: ModelIR, field: IRField): string {
  let type: string;
  if (field.type.startsWith("entity:")) type = "string";
  else if (field.type.startsWith("set:enum:")) type = `${enumName(ir, field.type)}[]`;
  else if (field.type.startsWith("enum:")) type = enumName(ir, field.type);
  else if (isMoneyType(field.type)) type = `Money<${JSON.stringify(moneyProfileFromType(field.type)!.currency)}>`;
  else type = ({ String: "string", Int: "number", Decimal: "string", Boolean: "boolean", UUID: "string", DateTime: "string" } as Record<string, string>)[field.type] ?? "never";
  return field.optional ? `${type} | null` : type;
}

function parameterType(ir: ModelIR, type: string): string {
  if (type.startsWith("entity:")) return "string";
  if (type.startsWith("set:enum:")) return `${enumName(ir, type)}[]`;
  if (type.startsWith("enum:")) return enumName(ir, type);
  if (isMoneyType(type)) return `Money<${JSON.stringify(moneyProfileFromType(type)!.currency)}>`;
  return ({ String: "string", Int: "number", Decimal: "string", Boolean: "boolean", UUID: "string", DateTime: "string" } as Record<string, string>)[type] ?? "never";
}

function inputName(action: IRAction): string {
  return `${action.name[0]!.toUpperCase()}${action.name.slice(1)}Input`;
}

function queryInputName(query: IRQuery): string {
  return `${query.name[0]!.toUpperCase()}${query.name.slice(1)}Input`;
}

function generateTypes(ir: ModelIR): string {
  const lines = ["// Generated by ModelLang. Do not edit.", ""];
  if (ir.entities.some((entity) => entity.fields.some((field) => isMoneyType(field.type)))
    || [...ir.actions, ...ir.queries].some((operation) => operation.parameters.some((parameter) => isMoneyType(parameter.type)))) {
    lines.push(
      "export interface Money<C extends string> {",
      "  readonly currency: C;",
      "  /** Exact base-10 amount; exponent notation and excess fractional digits are invalid. */",
      "  readonly amount: string;",
      "}",
      "",
    );
  }
  for (const enumeration of ir.enums) {
    lines.push(`export type ${enumeration.name} = ${enumeration.members.map((member) => JSON.stringify(member.naming.typescriptValue)).join(" | ")};`, "");
  }
  for (const entity of ir.entities) {
    lines.push(`export interface ${entity.name} {`);
    for (const field of entity.fields) {
      if (field.storage === "snapshot") lines.push("  /** Stored point-in-time snapshot; it is not re-derived from a related entity. */");
      if (field.generation) lines.push(`  /** Generated by the database using ${field.generation.strategy}; immutable after creation. */`);
      else if (field.mutability === "immutable") lines.push("  /** Immutable after creation. */");
      lines.push(`  ${field.name}: ${tsType(ir, field)};`);
    }
    lines.push("}", "");
  }
  for (const action of ir.actions) {
    lines.push(`export interface ${inputName(action)} {`);
    for (const id of action.callableParameters) {
      const parameter = action.parameters.find((candidate) => candidate.id === id)!;
      lines.push(`  ${parameter.name}: ${parameterType(ir, parameter.type)};`);
    }
    lines.push("}", "");
  }
  for (const query of ir.queries) {
    lines.push(`export interface ${queryInputName(query)} {`);
    for (const id of query.callableParameters) {
      const parameter = query.parameters.find((candidate) => candidate.id === id)!;
      lines.push(`  ${parameter.name}: ${parameterType(ir, parameter.type)};`);
    }
    lines.push("}", "");
  }
  return `${lines.join("\n")}\n`;
}

const errorsSource = `// Generated by ModelLang. Do not edit.
export class ModelDatabaseError extends Error {
  constructor(message: string, readonly code?: string, readonly ruleId?: string, readonly cause?: unknown) {
    super(message);
    this.name = new.target.name;
  }
}
export class IdentityBindingError extends ModelDatabaseError {}
export class AuthorizationError extends ModelDatabaseError {}
export class PreconditionError extends ModelDatabaseError {}
export class TransitionError extends ModelDatabaseError {}
export class InvariantError extends ModelDatabaseError {}
export class ConflictError extends ModelDatabaseError {}
export class NotFoundError extends ModelDatabaseError {}
export class ValidationError extends ModelDatabaseError {}

interface DatabaseFailure { code?: string; message?: string; constraint?: string }
export function mapDatabaseError(error: unknown): ModelDatabaseError {
  if (error instanceof ModelDatabaseError) return error;
  const value = error as DatabaseFailure;
  const message = value?.message ?? "Model database operation failed";
  const suffix = message.includes(":") ? message.slice(message.indexOf(":") + 1) : undefined;
  if (message.startsWith("ML_IDENTITY_UNBOUND")) return new IdentityBindingError(message, value.code, "boundary:principal_binding", error);
  if (message.startsWith("ML_AUTHORIZATION:")) return new AuthorizationError(message, value.code, suffix, error);
  if (message.startsWith("ML_PRECONDITION:")) return new PreconditionError(message, value.code, suffix, error);
  if (message.startsWith("ML_WORKFLOW:")) return new TransitionError(message, value.code, suffix, error);
  if (message.startsWith("ML_NOT_FOUND:")) return new NotFoundError(message, value.code, suffix, error);
  if (message.startsWith("ML_VALIDATION:")) return new ValidationError(message, value.code, suffix, error);
  if (value?.code === "23P01") return new ConflictError(message, value.code, value.constraint, error);
  if (value?.code === "23514" || value?.code === "23502" || value?.code === "23503" || value?.code === "23505") {
    return new InvariantError(message, value.code, value.constraint, error);
  }
  return new ModelDatabaseError(message, value?.code, undefined, error);
}
`;

function clientParameterValue(parameter: { id: string; name: string; type: string }): string {
  if (!isMoneyType(parameter.type)) return `input.${parameter.name}`;
  const profile = moneyProfileFromType(parameter.type)!;
  return `moneyAmount(input.${parameter.name}, ${JSON.stringify(profile.currency)}, ${profile.precision}, ${profile.scale}, ${JSON.stringify(`money-parameter:${parameter.id}`)})`;
}

function actionMethod(ir: ModelIR, action: IRAction): string {
  const returnEntity = ir.entities.find((entity) => entity.id === action.returnEntityId)!;
  const args = action.callableParameters.map((id, index) => {
    const parameter = action.parameters.find((candidate) => candidate.id === id)!;
    return { parameter, placeholder: `$${index + 1}` };
  });
  const schema = ir.model.naming.sqlSchema.replaceAll('"', '""');
  const fn = action.naming.sqlFunction.replaceAll('"', '""');
  return `  async ${action.name}(input: ${inputName(action)}): Promise<${returnEntity.name}> {
    try {
      const result = await this.adapter.query<{ value: ${returnEntity.name} }>(
        'SELECT "${schema}"."${fn}"(${args.map((arg) => arg.placeholder).join(", ")}) AS value',
        [${args.map((arg) => clientParameterValue(arg.parameter)).join(", ")}],
      );
      return result.rows[0]!.value;
    } catch (error) {
      throw mapDatabaseError(error);
    }
}`;
}

function queryMethod(ir: ModelIR, query: IRQuery): string {
  const sourceEntity = ir.entities.find((entity) => entity.id === query.sourceEntityId)!;
  const args = query.callableParameters.map((id, index) => {
    const parameter = query.parameters.find((candidate) => candidate.id === id)!;
    return { parameter, placeholder: `$${index + 1}` };
  });
  const schema = ir.model.naming.sqlSchema.replaceAll('"', '""');
  const fn = query.naming.sqlFunction.replaceAll('"', '""');
  return `  async ${query.name}(input: ${queryInputName(query)}): Promise<${sourceEntity.name}[]> {
    try {
      const result = await this.adapter.query<{ value: ${sourceEntity.name}[] }>(
        'SELECT "${schema}"."${fn}"(${args.map((arg) => arg.placeholder).join(", ")}) AS value',
        [${args.map((arg) => clientParameterValue(arg.parameter)).join(", ")}],
      );
      return result.rows[0]!.value;
    } catch (error) {
      throw mapDatabaseError(error);
    }
  }`;
}

function generateClient(ir: ModelIR): string {
  const imports = [...new Set([
    ...ir.entities.map((entity) => entity.name),
    ...ir.actions.map(inputName),
    ...ir.queries.map(queryInputName),
  ])];
  const hasMoneyInputs = [...ir.actions, ...ir.queries].some((operation) =>
    operation.callableParameters.some((id) => isMoneyType(operation.parameters.find((parameter) => parameter.id === id)!.type)));
  const moneyHelper = hasMoneyInputs ? `
function moneyAmount(
  value: { currency: string; amount: string },
  expectedCurrency: string,
  precision: number,
  scale: number,
  ruleId: string,
): string {
  const match = typeof value?.amount === "string"
    ? /^-?(0|[1-9][0-9]*)(?:\\.([0-9]+))?$/.exec(value.amount)
    : null;
  const integralDigits = match ? (match[1] === "0" ? 1 : match[1]!.length) : 0;
  const fractionalDigits = match?.[2]?.length ?? 0;
  if (value?.currency !== expectedCurrency || !match
    || integralDigits > precision - scale || fractionalDigits > scale) {
    throw new ValidationError(
      \`Invalid \${expectedCurrency} money value for \${ruleId}\`,
      undefined,
      ruleId,
    );
  }
  return value.amount;
}
` : "";
  return `// Generated by ModelLang. Do not edit.
import type { ${imports.join(", ")} } from "./types.js";
import { ${hasMoneyInputs ? "ValidationError, " : ""}mapDatabaseError } from "./errors.js";

export interface QueryAdapter {
  query<Row = unknown>(text: string, values?: unknown[]): Promise<{ rows: Row[] }>;
}
${moneyHelper}

export class ${ir.model.name}Client {
  constructor(private readonly adapter: QueryAdapter) {}

${[
    ...ir.actions.map((action) => actionMethod(ir, action)),
    ...ir.queries.map((query) => queryMethod(ir, query)),
  ].join("\n\n")}
}
`;
}

function generateWorkflows(ir: ModelIR): string {
  const lines = ["// Generated by ModelLang. Do not edit.", ""];
  for (const workflow of ir.workflows) {
    const enumeration = ir.enums.find((candidate) => candidate.id === workflow.enumId)!;
    const memberName = (id: string) => enumeration.members.find((candidate) => candidate.id === id)!.name;
    const actionName = (id: string) => ir.actions.find((candidate) => candidate.id === id)!.name;
    lines.push(
      `export const ${workflow.naming.typescriptName} = {`,
      `  initial: ${JSON.stringify(memberName(workflow.initialMemberId))},`,
      "  transitions: [",
      ...workflow.transitions.map((transition) =>
        `    { name: ${JSON.stringify(transition.name)}, from: ${JSON.stringify(memberName(transition.fromMemberId))}, to: ${JSON.stringify(memberName(transition.toMemberId))}, action: ${JSON.stringify(actionName(transition.actionId))} },`),
      "  ],",
      "} as const;",
      "",
    );
  }
  return `${lines.join("\n").trimEnd()}\n`;
}

export function generateTypeScript(ir: ModelIR): TypeScriptOutput {
  return {
    "types.ts": generateTypes(ir),
    "errors.ts": errorsSource,
    "client.ts": generateClient(ir),
    "workflows.ts": generateWorkflows(ir),
    "index.ts": `export * from "./types.js";\nexport * from "./errors.js";\nexport * from "./client.js";\nexport * from "./workflows.js";\n`,
  };
}
