import { stableJson } from "../ir.js";
import { operationInputName } from "../operation-manifest.js";
import type { OperationManifest } from "../operation-manifest.js";
import type { UiManifest } from "../ui-manifest.js";

export interface UiOutput {
  "typescript/ui.ts": string;
}

function resultType(manifest: OperationManifest, entityId: string, many: boolean): string {
  const entity = manifest.entities.find((candidate) => candidate.id === entityId);
  if (!entity) throw new Error(`E6202 Missing UI result entity '${entityId}'.`);
  return many ? `${entity.name}[]` : entity.name;
}

export function generateUi(manifest: OperationManifest, uiManifest: UiManifest): UiOutput {
  const imports = [...new Set([
    ...manifest.operations.map((operation) => resultType(manifest, operation.output.entityId, false)),
    ...manifest.operations.map(operationInputName),
  ])];
  const operationIds = manifest.operations.map((operation) => JSON.stringify(operation.id)).join(" | ");
  const inputMap = manifest.operations.map((operation) =>
    `  ${JSON.stringify(operation.id)}: ${operationInputName(operation)};`,
  ).join("\n");
  const resultMap = manifest.operations.map((operation) =>
    `  ${JSON.stringify(operation.id)}: ${resultType(manifest, operation.output.entityId, operation.kind === "query")};`,
  ).join("\n");
  const dispatch = manifest.operations.map((operation) =>
    `        case ${JSON.stringify(operation.id)}:\n          return await client.${operation.name}(input as unknown as ${operationInputName(operation)}) as ${manifest.model.name}UiResultByOperationId[Id];`,
  ).join("\n");
  return {
    "typescript/ui.ts": `// Generated by ModelLang. Do not edit.
import type { ${imports.join(", ")} } from "./types.js";
import { ValidationError } from "./errors.js";
import { ${manifest.model.name}HttpClient } from "./http-client.js";

/** Framework-neutral descriptors. Labels are generated defaults; stable IDs are binding keys. */
export const ${manifest.model.name}UiManifest = ${stableJson(uiManifest).trimEnd()} as const;

export type ${manifest.model.name}UiOperationId = ${operationIds};

export interface ${manifest.model.name}UiInputByOperationId {
${inputMap}
}

export interface ${manifest.model.name}UiResultByOperationId {
${resultMap}
}

export interface ${manifest.model.name}UiExecutor {
  execute<Id extends ${manifest.model.name}UiOperationId>(
    operationId: Id,
    input: ${manifest.model.name}UiInputByOperationId[Id],
  ): Promise<${manifest.model.name}UiResultByOperationId[Id]>;
}

/** Execute a manifest operation through the authenticated HTTP client. */
export function create${manifest.model.name}UiExecutor(client: ${manifest.model.name}HttpClient): ${manifest.model.name}UiExecutor {
  return {
    async execute<Id extends ${manifest.model.name}UiOperationId>(
      operationId: Id,
      input: ${manifest.model.name}UiInputByOperationId[Id],
    ): Promise<${manifest.model.name}UiResultByOperationId[Id]> {
      switch (operationId) {
${dispatch}
        default:
          throw new ValidationError("Unknown ModelLang UI operation", "ML_UI_OPERATION_NOT_FOUND", "ui:operation");
      }
    },
  };
}
`,
  };
}
