import { stableJson } from "../ir.js";
import { operationInputName } from "../operation-manifest.js";
import type { OperationManifest } from "../operation-manifest.js";
import type { UiManifest } from "../ui-manifest.js";

export interface UiOutput {
  "typescript/ui.ts": string;
}

function resultType(manifest: OperationManifest, entityId: string, many: boolean): string {
  const entity = manifest.entities.find((candidate) => candidate.id === entityId);
  if (!entity) throw new Error(`E6202 Missing UI result entity '${entityId}'.`);
  return many ? `${entity.name}[]` : entity.name;
}

export function generateUi(manifest: OperationManifest, uiManifest: UiManifest): UiOutput {
  const workflowEnums = manifest.workflows.map((workflow) => {
    const enumeration = manifest.enums.find((candidate) => candidate.id === workflow.enumId);
    if (!enumeration) throw new Error(`E6203 Missing UI workflow enum '${workflow.enumId}'.`);
    return enumeration.name;
  });
  const imports = [...new Set([
    ...manifest.operations.map((operation) => resultType(manifest, operation.output.entityId, false)),
    ...manifest.operations.map(operationInputName),
    ...workflowEnums,
  ])];
  const operationIds = manifest.operations.map((operation) => JSON.stringify(operation.id)).join(" | ");
  const inputMap = manifest.operations.map((operation) =>
    `  ${JSON.stringify(operation.id)}: ${operationInputName(operation)};`,
  ).join("\n");
  const resultMap = manifest.operations.map((operation) =>
    `  ${JSON.stringify(operation.id)}: ${resultType(manifest, operation.output.entityId, operation.kind === "query")};`,
  ).join("\n");
  const dispatch = manifest.operations.map((operation) =>
    `        case ${JSON.stringify(operation.id)}:\n          return await client.${operation.name}(input as unknown as ${operationInputName(operation)}) as ${manifest.model.name}UiResultByOperationId[Id];`,
  ).join("\n");
  const workflowIds = manifest.workflows.length
    ? manifest.workflows.map((workflow) => JSON.stringify(workflow.id)).join(" | ")
    : "never";
  const transitions = manifest.workflows.flatMap((workflow) => workflow.transitions);
  const transitionIds = transitions.length
    ? transitions.map((transition) => JSON.stringify(transition.id)).join(" | ")
    : "never";
  const workflowStateMap = manifest.workflows.map((workflow) => {
    const enumeration = manifest.enums.find((candidate) => candidate.id === workflow.enumId)!;
    return `  ${JSON.stringify(workflow.id)}: ${enumeration.name};`;
  }).join("\n");
  const transitionInputMap = transitions.map((transition) => {
    const action = manifest.operations.find((candidate) => candidate.id === transition.actionId && candidate.kind === "action")!;
    const input = operationInputName(action);
    const type = `Omit<${input}, ${JSON.stringify(transition.target.name)}>`;
    return `  ${JSON.stringify(transition.id)}: ${type};`;
  }).join("\n");
  const transitionResultMap = transitions.map((transition) => {
    const action = manifest.operations.find((candidate) => candidate.id === transition.actionId && candidate.kind === "action")!;
    return `  ${JSON.stringify(transition.id)}: ${resultType(manifest, action.output.entityId, false)};`;
  }).join("\n");
  const transitionDispatch = transitions.map((transition) => {
    const action = manifest.operations.find((candidate) => candidate.id === transition.actionId && candidate.kind === "action")!;
    return `        case ${JSON.stringify(transition.id)}:\n          return await client.${action.name}({ ...(input as object), [${JSON.stringify(transition.target.name)}]: targetId } as unknown as ${operationInputName(action)}) as ${manifest.model.name}UiTransitionResultById[Id];`;
  }).join("\n");
  return {
    "typescript/ui.ts": `// Generated by ModelLang. Do not edit.
import type { ${imports.join(", ")} } from "./types.js";
import { ValidationError } from "./errors.js";
import { ${manifest.model.name}HttpClient } from "./http-client.js";

/** Framework-neutral descriptors. Labels are generated defaults; stable IDs are binding keys. */
export const ${manifest.model.name}UiManifest = ${stableJson(uiManifest).trimEnd()} as const;

export type ${manifest.model.name}UiOperationId = ${operationIds};

export interface ${manifest.model.name}UiInputByOperationId {
${inputMap}
}

export interface ${manifest.model.name}UiResultByOperationId {
${resultMap}
}

export interface ${manifest.model.name}UiExecutor {
  execute<Id extends ${manifest.model.name}UiOperationId>(
    operationId: Id,
    input: ${manifest.model.name}UiInputByOperationId[Id],
  ): Promise<${manifest.model.name}UiResultByOperationId[Id]>;
}

/** Execute a manifest operation through the authenticated HTTP client. */
export function create${manifest.model.name}UiExecutor(client: ${manifest.model.name}HttpClient): ${manifest.model.name}UiExecutor {
  return {
    async execute<Id extends ${manifest.model.name}UiOperationId>(
      operationId: Id,
      input: ${manifest.model.name}UiInputByOperationId[Id],
    ): Promise<${manifest.model.name}UiResultByOperationId[Id]> {
      switch (operationId) {
${dispatch}
        default:
          throw new ValidationError("Unknown ModelLang UI operation", "ML_UI_OPERATION_NOT_FOUND", "ui:operation");
      }
    },
  };
}

export type ${manifest.model.name}UiWorkflowId = ${workflowIds};
export type ${manifest.model.name}UiTransitionId = ${transitionIds};
export type ${manifest.model.name}UiWorkflow = (typeof ${manifest.model.name}UiManifest.workflows)[number];
export type ${manifest.model.name}UiWorkflowTransition =
  ${manifest.model.name}UiWorkflow extends { transitions: readonly (infer Transition)[] } ? Transition : never;

export interface ${manifest.model.name}UiWorkflowStateById {
${workflowStateMap}
}

export interface ${manifest.model.name}UiTransitionInputById {
${transitionInputMap}
}

export interface ${manifest.model.name}UiTransitionResultById {
${transitionResultMap}
}

/** Return state-matching edges only. Authorization and preconditions remain server-enforced. */
export function available${manifest.model.name}UiTransitions<Id extends ${manifest.model.name}UiWorkflowId>(
  workflowId: Id,
  state: ${manifest.model.name}UiWorkflowStateById[Id],
): readonly ${manifest.model.name}UiWorkflowTransition[] {
  const workflows = ${manifest.model.name}UiManifest.workflows as readonly {
    workflowId: string;
    transitions: readonly { fromValue: string }[];
  }[];
  const workflow = workflows.find((candidate) => candidate.workflowId === workflowId);
  if (!workflow) throw new ValidationError("Unknown ModelLang UI workflow", "ML_UI_WORKFLOW_NOT_FOUND", "ui:workflow");
  return workflow.transitions.filter((transition) => transition.fromValue === state) as unknown as readonly ${manifest.model.name}UiWorkflowTransition[];
}

export interface ${manifest.model.name}UiWorkflowExecutor {
  available<Id extends ${manifest.model.name}UiWorkflowId>(
    workflowId: Id,
    state: ${manifest.model.name}UiWorkflowStateById[Id],
  ): readonly ${manifest.model.name}UiWorkflowTransition[];
  executeTransition<Id extends ${manifest.model.name}UiTransitionId>(
    transitionId: Id,
    targetId: string,
    input: ${manifest.model.name}UiTransitionInputById[Id],
  ): Promise<${manifest.model.name}UiTransitionResultById[Id]>;
}

/** Bind workflow targets and execute only declared transition actions through authenticated HTTP. */
export function create${manifest.model.name}UiWorkflowExecutor(
  client: ${manifest.model.name}HttpClient,
): ${manifest.model.name}UiWorkflowExecutor {
  return {
    available: available${manifest.model.name}UiTransitions,
    async executeTransition<Id extends ${manifest.model.name}UiTransitionId>(
      transitionId: Id,
      targetId: string,
      input: ${manifest.model.name}UiTransitionInputById[Id],
    ): Promise<${manifest.model.name}UiTransitionResultById[Id]> {
      switch (transitionId) {
${transitionDispatch}
        default:
          throw new ValidationError("Unknown ModelLang UI transition", "ML_UI_TRANSITION_NOT_FOUND", "ui:transition");
      }
    },
  };
}
`,
  };
}
